global:
  scrape_interval: 15s
  evaluation_interval: 15s #added
scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']
    # metrics_path: '/tam-metrics'  
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'alertmanager'
    scrape_interval: 5s
    static_configs:
      - targets: ['alertmanager:9093']
  # - job_name: 'promtail'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['promtail:9090']

rule_files:
  - rules.yaml
alerting:

  alertmanagers:

    - scheme: http

      static_configs:

#        - targets: [ 'alertmanager:9093', 'loki:3100', 'node-exporter:9100','cadvisor:8080' ]
        - targets: [ 'grafana-alertmanager-1:9093', 'grafana-loki-1:3100', 'node-exporter:9100','grafana-cadvisor-1:8080' ]        