# apiVersion: 1

# datasources:
#   - name: Prometheus
#     type: prometheus
#     access: proxy
#     url: http://prometheus:9090
#     isDefault: true

# For configuration options, see 
#   https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file

# apiVersion: 1

# datasources:
#   - name: Loki
#     type: loki
#     access: proxy
#     url: http://loki:3100
#     jsonData:
#       maxLines: 1000
#       timeout: 30
#     isDefault: true
#     editable: false

############### from documentation  https://grafana.com/docs/grafana/latest/datasources/prometheus/
apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100

  - name: Prometheus
    type: prometheus
    access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url:  http://prometheus:9090  #http://172.19.0.3:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.54.1
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      exemplarTraceIdDestinations:
        # Field with internal link pointing to data source in Grafana.
        # datasourceUid value can be anything, but it should be unique across all defined data source uids.
        - datasourceUid: my_jaeger_uid
          name: traceID

        # Field with external link.
        - name: traceID
          url: '172.19.0.3:3000/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Jaeger%22,%7B%22query%22:%22$${__value.raw}%22%7D%5D'